/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utils.JTabbedPaneCloseButton;
import Utils.LookAndFeel;
import java.awt.HeadlessException;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hoang Tran < hoang at 99.hoangtran@gmail.com >
 */
public class ManagerGUI extends JFrame implements Runnable {

    ServerSocket socket;
    DataInputStream is;
    DataOutputStream os;

    JTabbedPaneCloseButton tpClients;

    /**
     * Creates new form ServerGUI
     */
    public ManagerGUI() {
        initComponents();

        setTitle("Chat Server");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        tpClients = new JTabbedPaneCloseButton();
        plClientsContainer.add(tpClients);
    }

    @Override
    public void run() {
        while (true) {
            try {
                // Chấp nhận kết nối từ Client
                Socket staffSocket = socket.accept();
                if (staffSocket != null) {
                    System.out.println("Client connected  top, tabcount = " + tpClients.getTabCount());

                    // Lấy tên của Client vừa nhắn tin cho Manager
                    // Có nhiều cách xử lý, đây là cách của mình
                    is = new DataInputStream(staffSocket.getInputStream());
                    String staffName = is.readUTF();

                    // Tạo ChatPanel và show nó vào cái TabbedPane, khá là đơn giản
                    ChatPanel chatPanel = new ChatPanel(staffSocket, "Manager", staffName);
                    tpClients.addTab(staffName, chatPanel);
                    chatPanel.updateUI();

                    System.out.println("Client connected, tabcount = " + tpClients.getTabCount());

                    // Chạy Thread ChatPanel để kiểm tra các tin nhắn đến và đi (Đã giải thích ở phần 1)
                    Thread t = new Thread(chatPanel);
                    t.start();
                }
            } catch (IOException e) {
                // Do not change this because it spawn try-catch many time while running thread!
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txPort = new javax.swing.JTextField();
        btnStartServer = new javax.swing.JButton();
        plClientsContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Manager Port");
        jPanel1.add(jLabel1);

        txPort.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txPort.setText("5000");
        jPanel1.add(txPort);

        btnStartServer.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnStartServer.setText("START SERVER");
        btnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartServerActionPerformed(evt);
            }
        });
        jPanel1.add(btnStartServer);

        plClientsContainer.setMinimumSize(new java.awt.Dimension(0, 400));
        plClientsContainer.setPreferredSize(new java.awt.Dimension(600, 322));
        plClientsContainer.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plClientsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plClientsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartServerActionPerformed
        //Cổng mặc định là 5000, bạn có thể đổi thành số bạn thích
        int port = 5000;

        try {
            //Kiểm tra dữ liệu nhập vào
            port = Integer.parseInt(txPort.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Can't start at this port, program will use the default port=8\nDetails: " + e,
                    "Error while read Port", JOptionPane.ERROR_MESSAGE);
        }

        try {
            //Hiểu nôm na là chạy Server tại port này
            socket = new ServerSocket(port);
            JOptionPane.showMessageDialog(this, "Server is running at port: " + port, "Started server",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(this, "Details: " + e, "Start server error",
                    JOptionPane.ERROR_MESSAGE);
        }

        //Chạy Server (class ManagerGUI hiên tại) để kiểm tra các luồng kết nối vào server sau này
        Thread t = new Thread(this);
        t.start();
    }//GEN-LAST:event_btnStartServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        LookAndFeel.setSystemLookAndFeel();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel plClientsContainer;
    private javax.swing.JTextField txPort;
    // End of variables declaration//GEN-END:variables
}
